#!/usr/bin/env bash

set -euo pipefail

BASE_URL_AUTH="http://localhost:8081/authstarter"
BASE_URL="http://localhost:8080/springstarter"

LOGIN_URL="${BASE_URL_AUTH}/auth/login"
SAMPLES_URL="${BASE_URL}/api/v1/samples"

USERNAME="admin"
PASSWORD="password"

echo "=== Authentication ==="

LOGIN_RESPONSE=$(curl --silent --show-error --fail-with-body \
  --request POST \
  "${LOGIN_URL}" \
  --header "Content-Type: application/json" \
  --data "{
    \"username\": \"${USERNAME}\",
    \"password\": \"${PASSWORD}\"
  }")

TOKEN=$(echo "${LOGIN_RESPONSE}" | jq -r '.accessToken')

if [[ -z "${TOKEN}" || "${TOKEN}" == "null" ]]; then
  echo "ERROR: Unable to retrieve authentication token."
  echo "Login response:"
  echo "${LOGIN_RESPONSE}"
  exit 1
fi

echo "Authentication successful."
echo


create_sample() {
  local index="$1"

  local name
  local description
  local quantity
  local stock
  local weight
  local ratio
  local price
  local active
  local category
  local manufactured_date
  local manufactured_time
  local external_id
  local comments
  local status
  local version

  name=$(printf "SAMPLE_%03d" "${index}")
  description="Sample generated by CURL script - ${index}"

  quantity=$((index * 10))
  stock=$((index * 5))

  weight=$((index * 10))
  ratio="0.50"

  price="${index}9.99"

  active="true"
  category="A"

  manufactured_date="2026-09-01"
  manufactured_time="10:30:00"

  external_id=$(cat /proc/sys/kernel/random/uuid)

  comments="Automatically generated sample ${index}"
  status="ACTIVE"
  version=$((index + 1))

  echo "Creating ${name}..."

  HTTP_CODE=$(curl -v --silent \
    --output "/tmp/sample-response-${index}.json" \
    --write-out "%{http_code}" \
    --request POST \
    "${SAMPLES_URL}" \
    --header "Authorization: Bearer ${TOKEN}" \
    --header "Content-Type: application/json" \
    --data "{
      \"name\": \"${name}\",
      \"description\": \"${description}\",
      \"quantity\": ${quantity},
      \"stock\": ${stock},
      \"weight\": ${weight},
      \"ratio\": ${ratio},
      \"price\": ${price},
      \"active\": ${active},
      \"category\": \"${category}\",
      \"manufacturedDate\": \"${manufactured_date}\",
      \"manufacturedTime\": \"${manufactured_time}\",
      \"externalId\": \"${external_id}\",
      \"document\": \"VGhpcyBpcyBhIHRlc3QgZG9jdW1lbnQ=\",
      \"comments\": \"${comments}\",
      \"status\": \"${status}\",
      \"version\": ${version}
    }")

  if [[ "${HTTP_CODE}" == "201" ]]; then
    echo "OK (${HTTP_CODE}) - ${name}"

    if command -v jq >/dev/null 2>&1; then
      jq \
        '{id, name, externalId, status, version}' \
        "/tmp/sample-response-${index}.json"
    else
      cat "/tmp/sample-response-${index}.json"
      echo
    fi
  else
    echo "ERROR (${HTTP_CODE}) - ${name}"
    cat "/tmp/sample-response-${index}.json"
    echo
  fi

  echo
}


echo "=== Creating samples ==="

for i in $(seq 1 20); do
  create_sample "${i}"
done

echo "=== Finished ==="

